[firebase]
apiKey = "AIzaSyD7-HwufkeY97nP5I61DZJaeCTNY7ccvKo"
authDomain = "gestawebds7raquelacioli.firebaseapp.com"
projectId = "gestawebds7raquelacioli"
storageBucket = "gestawebds7raquelacioli.appspot.com"
messagingSenderId = "536966961533"
appId = "1:536966961533:web:1f4b0bfe25f60799c31414"
databaseURL = "https://gestawebds7raquelacioli.firebaseio.com" 

[paths]
# caminho para o JSON da Service Account (Firebase Admin)
service_account_json = "service_account.json"

[app]
force_unit_lock = true

